### ISSUE TITLE
Flow Chart

### ISSUE THREAD

**Issue by rossm933** [nss-evening-cohort-26/pos-terminal-pixel-pioneers#28]
# User Story
Flow chart of the app. 

# Acceptance Criteria
Flow chart breaking down the different sections of the app. 

# Dependecies
No other dependencies, part of setup.  

# Dev Notes
https://docs.google.com/presentation/d/1S79N6hope3l9MJW8cXNxuKG3k3gesV6euWHbhqsxK7U/edit?usp=sharing

**Comment by Zpcolburn** [comment]
Created Flow chart. 
Added link to google slides.
