### ISSUE TITLE
READ - Add/Edit and item page

### ISSUE THREAD

**Issue by FletcherJMoore** [nss-evening-cohort-26/pos-terminal-pixel-pioneers#33]
# User Story
You have been contacted by the owner of a business and they want you to add a new feature to their website. The owner would like to add a form so that any authenticated users can add a new item to purchase.

# Acceptance Criteria
When the user clicks the Add Item button on the dom it should take them to a new page where they can fill out the necessary information that they want to put on the item card. The form should include: 
1. Item Name
2. Item Price
3. Add Item button that when clicked submits the new item card and places it on the items page.

Note: This does not need to be functional yet. You are simply making the format so when the team working on create can focus on the event listeners and API calls. 

# Dev Notes
1. Create a addItem.js file using the git touch command and place it in the necessary folder so it is easy for your team to find and edit if necessary
2. Import and export the necessary files for this page
3. format the page so there are two text boxes that are labeled "Item Name" and "Item Price" for the user to be able to type in the information they need.
4. Add a submit button below the text boxes

Here is an example of what we
![Screenshot 2024-03-12 181236](https://github.com/nss-evening-cohort-26/pos-terminal-pixel-pioneers/assets/154636617/d5ce69f6-7359-4de0-b67a-a5358660c3ca)
're looking for:

**Comment by taylorseager** [comment]
I have created a addItem.js file and am currently working on that :)
