### ISSUE TITLE
closeOrderForm.js

### ISSUE THREAD

**Issue by rossm933** [nss-evening-cohort-26/pos-terminal-pixel-pioneers#38]
# Acceptance Criteria
create selectPaymentOption.js file under forms. 

# Dependecies
![image](https://github.com/nss-evening-cohort-26/pos-terminal-pixel-pioneers/assets/148557558/df81ba3e-bc54-431c-85ee-88c4a25e1b14)

**Comment by taylorseager** [comment]
Initially thought we would need this function, but during decided it was not needed. We chose to do a select tag within the template literal within the close order form instead.
